// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrations/push용으로는 Session Mode(5432)인 DIRECT_URL을 사용합니다.
    url: process.env["DIRECT_URL"],
  },
});
